### ISSUE TITLE
Show the 'normal / abnormal' calculation in list views

### ISSUE THREAD

**Issue by willscott** [ooni/explorer-legacy#80]
Currently, when viewing a single http_requests test, the explorer shows a status indicator of whether the test behaved normally or not.  Since much of the point of the explorer to is to explore abnormal tests, that should be shown when looking through the listing of tests for a specific country.

**Comment by hellais** [comment]
Yes this is a very good point and a known limitation of the current data processing pipeline.

I will try to summarise here what is the current implementation and what needs to be done in order to support what you, rightfully so, suggest.

## Current implementation

Data is transformed in batch with a periodicity of 24 hours and it's sliced up in a way that it can fit inside of the database. Every measurement (that is one entry inside of an OONI report) is put inside of a the metrics table (this is it's schema: https://github.com/TheTorProject/ooni-pipeline/blob/master/pipeline/batch/daily_workflow.py#L759) one measurement per row.

There are then 4 materialised views, blockpage_count, blockpage_urls, identified_vendors, country_counts, that keep track of respectively the number of blockpages detected per test run per country, the URLs that are detected as being blocked, the vendors that have been identified and the total number of measurements per country.
These materialised views are specified inside of this batch task (that also has a periodicity of 24 hours) https://github.com/TheTorProject/ooni-pipeline/blob/master/pipeline/batch/sql_tasks.py#L208 and mainly rely on string matching to detect the presence of a blockpage. You can find the heuristics that we currently support here: https://github.com/TheTorProject/ooni-pipeline/blob/master/pipeline/batch/sql_tasks.py#L10.

When you open the measurement view the detection of the anomaly is actually done client side in javascript, by looking at the `body_length_match`, `control_failure`, `experiment_failure` and `headers_match` keys of the report to determine if there is an anomaly.

Because of this there is even a mis-alignment between the client side heuristic and the materialised view heuristic, that can lead to sometimes confusing measurement pages (for example, it could be that the control did not succeed, but we are still able to infer censorship by the presence of a blockpage, though this means that the client side heuristics will not work, while the materialised views ones will).

## Proposed changes

What I propose to be done in the following iteration of the pipeline is integrate the blockpage detection and client side based heuristics in the first batch task (before inserting them into the database). This would require changing the schema of the database to include 2 extra fields `blockpage_detected` (maybe we should rename this as something other than blockpage since we may want to apply this also to DNS resolutions when we see the resolved IP to be that of a censor) and `anomaly` (for the heuristics that are currently done in the client).

This however would require that we re-run the data pipeline on all historical data and make quite a bit of changes to the explorer. However in doing so it would be much easier to then filter in the list view the measurements that are not anomalous from the anomalous ones.

**Comment by hellais** [comment]
This is implemented in the new OONI Explorer 🎉
